spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: credit_admin
    password: credit_admin
    driver-class-name: oracle.jdbc.driver.OracleDriver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath:mapper/*.xml  #sql映射文件位置

person:
  name: zhangsan