spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath:mapper/*.xml  #sql映射文件位置

#person:
  #name: test_zhangsan